### ISSUE TITLE
Profile View Does Not Play Well With PyPlot

### ISSUE THREAD

**Issue by UserQuestions** [timholy/ProfileView.jl#102]
When I call `PyPlot` after calling `ProfileView`, I get the following error:

```
sys:1: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'Qt5Agg' by the following code:
  File "/home/.julia/packages/Conda/m7vem/deps/usr/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


Warning: No working GUI backend found for matplotlib
@ PyPlot ~/.julia/packages/PyPlot/fZuOQ/src/init.jl:160
```

I suspect that `ProfileView` is changing some setting for the backend that `PyPlot` needs.  When I try using `PyPlot` before `ProfileView`, it just hangs on `ProfileView` and never does anything.

**Comment by timholy** [comment]
Might be https://github.com/JuliaGraphics/Gtk.jl/issues/193? (Maybe try the WebAgg backend?) I'm puzzled though because it seems that it should already be non-conflicting.

In any event, this is a [Gtk.jl](https://github.com/JuliaGraphics/Gtk.jl) bug and there's nothing ProfileView can do to fix it short of not using Gtk, so I'll close this.
