### ISSUE TITLE
scroll-zoom interaction the web view is unusable

### ISSUE THREAD

**Issue by StefanKarpinski** [timholy/ProfileView.jl#69]
I always hate scroll zoom interfaces but this one is particularly bad. Is there a way to turn it off and just display a fixed-size flame graph? Can it be turned off by default?

**Comment by timholy** [comment]
Just to clarify, do your concerns also apply to the Gtk version? Since I don't know javascript and don't plan on learning, I've deferred to others when it comes to how the web version should work. But if similar concerns apply to the Gtk version, I'd be happy to make revisions.

**Comment by StefanKarpinski** [comment]
I haven't tried the Gtk version, but the if it uses scroll to zoom, then yes :) I think that scroll to zoom was designed for an works less horribly with scroll mice (although I don't care for it there either), but for trackpads with scroll support (including all non-ancient Apple laptops), it's a disaster. This does seem to apply to all Compose-based web UIs, so perhaps the root and I should open the issue there. In the interest of having a default setup that works for everyone, this kind of thing should be opt-in. cc: @shashi who may know what package to blame for this behavior 😁

**Comment by timholy** [comment]
Interesting. Can you point me to a description or example of an interface you prefer? E.g., pinch-zoom? My experience may be biased by my early decision (in more idealistic days) to boycott apple products and only use Linux (which is now just a habit, not a principle), where my trackpad seems to behave roughly the same way as it did 15 years ago (though perhaps that too is just my habits speaking).

As long as I have a wheel mouse, I find it incredibly efficient, especially since this one (at least in the Gtk interface) lets me zoom in and out focused on the pointer location. Much better, say, than google maps where zooming in forces me to move my mouse to a specific button and click it.

I suspect with Gtk it's possible to query what type of mouse/trackpad/etc, so it should be "easy" to make it opt in and/or default to something based on availability of multitouch/wheel mouse/etc.

**Comment by StefanKarpinski** [comment]
I think this interface works well for a wheel mouse, but it's terrible with a trackpad that supports scroll – which is most of them these days, Apple or not. Selecting a region to zoom to is a pretty classic and intuitive interface. You need some way to zoom out as well, I'm not sure what that would be.

**Comment by timholy** [comment]
Totally willing to change the Gtk side. When I don't have a wheelmouse handy, I agree with you that it's almost unusable. As a model, can you direct me to an application you like?

If you want some fun and have a wheel mouse, sometime try the `demos/julia_gui.jl` demo in GtkUtilities. Point your mouse over a tiny feature you'd like to zoom in and out on (not necessarily in the center of the image), hold down CTRL, and then scroll in and out. I use that day in and day out for interactive data exploration, and it's so friggin productive I almost scream when using other interfaces. But it's crucially dependent on that wheel.

**Comment by timholy** [comment]
I dug into this a big recently. It seems that a two-finger drag also caused zooming in the Gtk version. In #74, you always have to hold down Ctrl to get zooming, so perhaps this addresses any concerns? Would be great if the web version could follow suit.

**Comment by timholy** [comment]
Works fine on GTK. Jupyter interaction has been taken over by https://github.com/timholy/ProfileSVG.jl
