### ISSUE TITLE
Minor window resizing graphical bug

### ISSUE THREAD

**Issue by miguelraz** [timholy/ProfileView.jl#72]
Running the example on the README.md, if I click-and-drag a box outside of the window size, the GUI glitches out.

**Comment by miguelraz** [comment]
Awesome work, thanks!
Hope I can help out with PR's in the future - I know that just raising issues isn't the most helpful thing to do.
Any comments/critiques/advice most welcome!

**Comment by timholy** [comment]
I should note that it won't really be fixed until #74 merges.

Just raising it is fine, it was a quick fix once the problem was pointed out. But if you like this stuff, I recommend taking a peek at GtkReactive, at least the [documentation](https://juliagizmos.github.io/GtkReactive.jl/stable/), to learn more about how to do mouse/canvas interaction.

**Comment by miguelraz** [comment]
I just ran into it recently - looks promising!
Albeit perhaps GLVisualize.jl weill be more akin to rendering some physics simulations...
