### ISSUE TITLE
Red makes it hard to distinguish functions

### ISSUE THREAD

**Issue by antoine-levitt** [timholy/ProfileView.jl#81]
I like the red labelling of type-unstable functions, but it makes it impossible to tell the difference between different functions. Would it be possible to add black boundaries to the rectangles?

**Comment by timholy** [comment]
Good idea. One could look for changes in `imgtags` and then draw a boundary line.

**Comment by antoine-levitt** [comment]
I tried to add an img[i,j] = fontcolor after line 286 of ProfileView.jl, which sort of works but that makes lines that are too big when the window is maximized. I've now reached my incompetence point, so hoping someone else will take this on!

**Comment by CarloLucibello** [comment]
updates on this?

**Comment by timholy** [comment]
It's actually not straightforward since the flamegraph is presented as a bitmap. There are now custom-coloration facilities in https://github.com/timholy/FlameGraphs.jl.

**Comment by timholy** [comment]
Since I've never been at all bothered by this (your profiles must be different from mine), I'm marking this as something to be added by a contributor.

Since FlameGraphs represents each row of the image as a single pixel high, it can't be added in FlameGraphs itself. You'll have to dig into Cairo and figure out how to draw the lines retrospectively.

**Comment by timholy** [comment]
Closed by https://github.com/timholy/FlameGraphs.jl/pull/9

**Comment by antoine-levitt** [comment]
I don't think that closed this issue? I'm still getting the same behavior after updating to ProfileView#master

**Comment by timholy** [comment]
Bump [compat] or just wait a bit
